-- Create main table if not exists
CREATE TABLE IF NOT EXISTS {bq_project}.{bq_dataset}.{table_name} (
    idAdmin INT64,
    adminName STRING,
    adminPassword STRING,
    adminLevel STRING,
    lastLogin TIMESTAMP,
    idSupplier INT64,
    idAffiliate INT64,
    canAddProducts INT64,
    canEditProducts INT64,
    canDeleteProducts INT64,
    canViewVendors INT64,
    canAddVendors INT64,
    canDeleteVendors INT64,
    canDeleteRegisteredProducts INT64,
    canEditRegisteredProducts INT64,
    adminInitials STRING,
    canRunSQL INT64,
    canUpdateStock INT64,
    canSearch INT64,
    canViewRegisteredProducts INT64,
    canEditAdmins INT64,
    canEditVendors INT64,
    canUpdateProducts INT64,
    canViewRegisteredCustomers INT64,
    canEditRegisteredCustomers INT64,
    canDeleteRegisteredCustomers INT64,
    canAddRegisteredCustomers INT64,
    canViewProducts INT64,
    canCustomExportToXL INT64,
    canModifyDescDet INT64,
    canUseCustomMessages INT64,
    idWarehouse INT64,
    ipaddresses STRING,
    useractive BOOL,
    emailid STRING,
    OrderLabel_PrinterName STRING,
    UPCLabel_PrinterName STRING,
    UPCPrintRights INT64,
    AllowPullAll INT64,
    UploadPath STRING,
    UPCALableSettings STRING,
    EAN13LabelSettings STRING,
    pUPC_LogOutTime FLOAT64,
    UPCScanFooterSetting INT64,
    GiftLabel_PrinterName STRING,
    InvoiceLabel_PrinterName STRING,
    IsLocked INT64,
    LockedIp STRING,
    LockedTime TIMESTAMP,
    IsUPCScanSaveLoginPassword INT64,
    FirstName STRING,
    LastName STRING,
    BadgeID INT64,
    EMPID INT64,
    isForceToChangePassword INT64,
    isAbleToSelectBox INT64,
    IdWarehouseForUPCScanPack INT64,
    UseNewSystem INT64,
    InventoryReadWrite INT64,
    ShippingLabel_PrinterName STRING,
    CustomImportReadWrite INT64,
    InventoryExportReadWrite INT64,
    ExportDatareadWrite INT64,
    AmazonUCCLabel_PrinterName STRING,
    PullPackReset INT64,
    CanDeleteOrder INT64,
    isResetEdi INT64,
    LogOffTime INT64,
    tracktime BOOL,
    TopCustomers FLOAT64,
    IsUpdateScripts INT64,
    isBuyer BOOL,
    isUpdateCustomerInformation INT64,
    isGlobalSupplierUpdate BOOL,
    RoutingRequestPermission BOOL,
    IsMantisReportView BOOL,
    isSupplierDelete BOOL,
    IsRefreshPortalDataView BOOL,
    POCustomerSelected STRING,
    ShipmentHDRVisibility STRING,
    showPOFromAllBuyer BOOL,
    IsReceivedQtyUpdate BOOL,
    RoleId INT64,
    IsExportCapability BOOL,
    IsReportCapability BOOL,
    IsSkuManager BOOL,
    IsCampaignManager BOOL,
    Country STRING,
    PrepareQtyCapability BOOL,
    LoginAttempt INT64,
    AmazonOrderTypeSelected STRING,
    FilteredAmazonPO STRING,
    FilteredAmazonSKU STRING
);

-- Merge data from temp table to main table
MERGE {bq_project}.{bq_dataset}.{table_name} AS MAIN
USING {bq_project}.{bq_dataset}.{temp_table_name} AS TEMP
ON MAIN.idAdmin = TEMP.idAdmin
WHEN MATCHED THEN
    UPDATE SET
        MAIN.idAdmin = TEMP.idAdmin,
        MAIN.adminName = TEMP.adminName,
        MAIN.adminPassword = TEMP.adminPassword,
        MAIN.adminLevel = TEMP.adminLevel,
        MAIN.lastLogin = TEMP.lastLogin,
        MAIN.idSupplier = TEMP.idSupplier,
        MAIN.idAffiliate = TEMP.idAffiliate,
        MAIN.canAddProducts = TEMP.canAddProducts,
        MAIN.canEditProducts = TEMP.canEditProducts,
        MAIN.canDeleteProducts = TEMP.canDeleteProducts,
        MAIN.canViewVendors = TEMP.canViewVendors,
        MAIN.canAddVendors = TEMP.canAddVendors,
        MAIN.canDeleteVendors = TEMP.canDeleteVendors,
        MAIN.canDeleteRegisteredProducts = TEMP.canDeleteRegisteredProducts,
        MAIN.canEditRegisteredProducts = TEMP.canEditRegisteredProducts,
        MAIN.adminInitials = TEMP.adminInitials,
        MAIN.canRunSQL = TEMP.canRunSQL,
        MAIN.canUpdateStock = TEMP.canUpdateStock,
        MAIN.canSearch = TEMP.canSearch,
        MAIN.canViewRegisteredProducts = TEMP.canViewRegisteredProducts,
        MAIN.canEditAdmins = TEMP.canEditAdmins,
        MAIN.canEditVendors = TEMP.canEditVendors,
        MAIN.canUpdateProducts = TEMP.canUpdateProducts,
        MAIN.canViewRegisteredCustomers = TEMP.canViewRegisteredCustomers,
        MAIN.canEditRegisteredCustomers = TEMP.canEditRegisteredCustomers,
        MAIN.canDeleteRegisteredCustomers = TEMP.canDeleteRegisteredCustomers,
        MAIN.canAddRegisteredCustomers = TEMP.canAddRegisteredCustomers,
        MAIN.canViewProducts = TEMP.canViewProducts,
        MAIN.canCustomExportToXL = TEMP.canCustomExportToXL,
        MAIN.canModifyDescDet = TEMP.canModifyDescDet,
        MAIN.canUseCustomMessages = TEMP.canUseCustomMessages,
        MAIN.idWarehouse = TEMP.idWarehouse,
        MAIN.ipaddresses = TEMP.ipaddresses,
        MAIN.useractive = TEMP.useractive,
        MAIN.emailid = TEMP.emailid,
        MAIN.OrderLabel_PrinterName = TEMP.OrderLabel_PrinterName,
        MAIN.UPCLabel_PrinterName = TEMP.UPCLabel_PrinterName,
        MAIN.UPCPrintRights = TEMP.UPCPrintRights,
        MAIN.AllowPullAll = TEMP.AllowPullAll,
        MAIN.UploadPath = TEMP.UploadPath,
        MAIN.UPCALableSettings = TEMP.UPCALableSettings,
        MAIN.EAN13LabelSettings = TEMP.EAN13LabelSettings,
        MAIN.pUPC_LogOutTime = TEMP.pUPC_LogOutTime,
        MAIN.UPCScanFooterSetting = TEMP.UPCScanFooterSetting,
        MAIN.GiftLabel_PrinterName = TEMP.GiftLabel_PrinterName,
        MAIN.InvoiceLabel_PrinterName = TEMP.InvoiceLabel_PrinterName,
        MAIN.IsLocked = TEMP.IsLocked,
        MAIN.LockedIp = TEMP.LockedIp,
        MAIN.LockedTime = TEMP.LockedTime,
        MAIN.IsUPCScanSaveLoginPassword = TEMP.IsUPCScanSaveLoginPassword,
        MAIN.FirstName = TEMP.FirstName,
        MAIN.LastName = TEMP.LastName,
        MAIN.BadgeID = TEMP.BadgeID,
        MAIN.EMPID = TEMP.EMPID,
        MAIN.isForceToChangePassword = TEMP.isForceToChangePassword,
        MAIN.isAbleToSelectBox = TEMP.isAbleToSelectBox,
        MAIN.IdWarehouseForUPCScanPack = TEMP.IdWarehouseForUPCScanPack,
        MAIN.UseNewSystem = TEMP.UseNewSystem,
        MAIN.InventoryReadWrite = TEMP.InventoryReadWrite,
        MAIN.ShippingLabel_PrinterName = TEMP.ShippingLabel_PrinterName,
        MAIN.CustomImportReadWrite = TEMP.CustomImportReadWrite,
        MAIN.InventoryExportReadWrite = TEMP.InventoryExportReadWrite,
        MAIN.ExportDatareadWrite = TEMP.ExportDatareadWrite,
        MAIN.AmazonUCCLabel_PrinterName = TEMP.AmazonUCCLabel_PrinterName,
        MAIN.PullPackReset = TEMP.PullPackReset,
        MAIN.CanDeleteOrder = TEMP.CanDeleteOrder,
        MAIN.isResetEdi = TEMP.isResetEdi,
        MAIN.LogOffTime = TEMP.LogOffTime,
        MAIN.tracktime = TEMP.tracktime,
        MAIN.TopCustomers = TEMP.TopCustomers,
        MAIN.IsUpdateScripts = TEMP.IsUpdateScripts,
        MAIN.isBuyer = TEMP.isBuyer,
        MAIN.isUpdateCustomerInformation = TEMP.isUpdateCustomerInformation,
        MAIN.isGlobalSupplierUpdate = TEMP.isGlobalSupplierUpdate,
        MAIN.RoutingRequestPermission = TEMP.RoutingRequestPermission,
        MAIN.IsMantisReportView = TEMP.IsMantisReportView,
        MAIN.isSupplierDelete = TEMP.isSupplierDelete,
        MAIN.IsRefreshPortalDataView = TEMP.IsRefreshPortalDataView,
        MAIN.POCustomerSelected = TEMP.POCustomerSelected,
        MAIN.ShipmentHDRVisibility = TEMP.ShipmentHDRVisibility,
        MAIN.showPOFromAllBuyer = TEMP.showPOFromAllBuyer,
        MAIN.IsReceivedQtyUpdate = TEMP.IsReceivedQtyUpdate,
        MAIN.RoleId = TEMP.RoleId,
        MAIN.IsExportCapability = TEMP.IsExportCapability,
        MAIN.IsReportCapability = TEMP.IsReportCapability,
        MAIN.IsSkuManager = TEMP.IsSkuManager,
        MAIN.IsCampaignManager = TEMP.IsCampaignManager,
        MAIN.Country = TEMP.Country,
        MAIN.PrepareQtyCapability = TEMP.PrepareQtyCapability,
        MAIN.LoginAttempt = TEMP.LoginAttempt,
        MAIN.AmazonOrderTypeSelected = TEMP.AmazonOrderTypeSelected,
        MAIN.FilteredAmazonPO = TEMP.FilteredAmazonPO,
        MAIN.FilteredAmazonSKU = TEMP.FilteredAmazonSKU
WHEN NOT MATCHED THEN
INSERT VALUES (
    TEMP.idAdmin,
    TEMP.adminName,
    TEMP.adminPassword,
    TEMP.adminLevel,
    TEMP.lastLogin,
    TEMP.idSupplier,
    TEMP.idAffiliate,
    TEMP.canAddProducts,
    TEMP.canEditProducts,
    TEMP.canDeleteProducts,
    TEMP.canViewVendors,
    TEMP.canAddVendors,
    TEMP.canDeleteVendors,
    TEMP.canDeleteRegisteredProducts,
    TEMP.canEditRegisteredProducts,
    TEMP.adminInitials,
    TEMP.canRunSQL,
    TEMP.canUpdateStock,
    TEMP.canSearch,
    TEMP.canViewRegisteredProducts,
    TEMP.canEditAdmins,
    TEMP.canEditVendors,
    TEMP.canUpdateProducts,
    TEMP.canViewRegisteredCustomers,
    TEMP.canEditRegisteredCustomers,
    TEMP.canDeleteRegisteredCustomers,
    TEMP.canAddRegisteredCustomers,
    TEMP.canViewProducts,
    TEMP.canCustomExportToXL,
    TEMP.canModifyDescDet,
    TEMP.canUseCustomMessages,
    TEMP.idWarehouse,
    TEMP.ipaddresses,
    TEMP.useractive,
    TEMP.emailid,
    TEMP.OrderLabel_PrinterName,
    TEMP.UPCLabel_PrinterName,
    TEMP.UPCPrintRights,
    TEMP.AllowPullAll,
    TEMP.UploadPath,
    TEMP.UPCALableSettings,
    TEMP.EAN13LabelSettings,
    TEMP.pUPC_LogOutTime,
    TEMP.UPCScanFooterSetting,
    TEMP.GiftLabel_PrinterName,
    TEMP.InvoiceLabel_PrinterName,
    TEMP.IsLocked,
    TEMP.LockedIp,
    TEMP.LockedTime,
    TEMP.IsUPCScanSaveLoginPassword,
    TEMP.FirstName,
    TEMP.LastName,
    TEMP.BadgeID,
    TEMP.EMPID,
    TEMP.isForceToChangePassword,
    TEMP.isAbleToSelectBox,
    TEMP.IdWarehouseForUPCScanPack,
    TEMP.UseNewSystem,
    TEMP.InventoryReadWrite,
    TEMP.ShippingLabel_PrinterName,
    TEMP.CustomImportReadWrite,
    TEMP.InventoryExportReadWrite,
    TEMP.ExportDatareadWrite,
    TEMP.AmazonUCCLabel_PrinterName,
    TEMP.PullPackReset,
    TEMP.CanDeleteOrder,
    TEMP.isResetEdi,
    TEMP.LogOffTime,
    TEMP.tracktime,
    TEMP.TopCustomers,
    TEMP.IsUpdateScripts,
    TEMP.isBuyer,
    TEMP.isUpdateCustomerInformation,
    TEMP.isGlobalSupplierUpdate,
    TEMP.RoutingRequestPermission,
    TEMP.IsMantisReportView,
    TEMP.isSupplierDelete,
    TEMP.IsRefreshPortalDataView,
    TEMP.POCustomerSelected,
    TEMP.ShipmentHDRVisibility,
    TEMP.showPOFromAllBuyer,
    TEMP.IsReceivedQtyUpdate,
    TEMP.RoleId,
    TEMP.IsExportCapability,
    TEMP.IsReportCapability,
    TEMP.IsSkuManager,
    TEMP.IsCampaignManager,
    TEMP.Country,
    TEMP.PrepareQtyCapability,
    TEMP.LoginAttempt,
    TEMP.AmazonOrderTypeSelected,
    TEMP.FilteredAmazonPO,
    TEMP.FilteredAmazonSKU
)
