-- Create main table if not exists
CREATE TABLE IF NOT EXISTS `{bq_project}.{bq_dataset}.{table_name}` (
    idcustomer INT64,
    name STRING,
    lastName STRING,
    customerCompany STRING,
    phone STRING,
    fax STRING,
    homephone STRING,
    mobile STRING,
    yearsinbiz STRING,
    annualsales STRING,
    productline STRING,
    lineofbiz STRING,
    comments STRING,
    lastlogin STRING,
    account STRING,
    taxid STRING,
    taxcheck FLOAT64,
    history STRING,
    email STRING,
    password STRING,
    address STRING,
    zip STRING,
    stateCode STRING,
    state STRING,
    city STRING,
    countryCode STRING,
    shippingName STRING,
    shippingLastName STRING,
    shippingaddress STRING,
    shippingcity STRING,
    shippingStateCode STRING,
    shippingState STRING,
    shippingCountryCode STRING,
    shippingZip INT64,
    wapAccess STRING,
    active FLOAT64,
    idCustomerType FLOAT64,
    refNumber STRING,
    status STRING,
    daterequested STRING,
    dateapproved STRING,
    idLanguage STRING,
    bonusPoints FLOAT64,
    flag STRING,
    handlingFee FLOAT64,
    myUpsFee FLOAT64,
    chargeActivationFee FLOAT64,
    canUseUPSaccount FLOAT64,
    fromShippingZip STRING,
    timesMailedHtml STRING,
    timesMailedText STRING,
    prefers STRING,
    confirmed STRING,
    dateSubscribed STRING,
    dateLastUpdated STRING,
    customSubField1 STRING,
    customSubField2 STRING,
    customSubField3 STRING,
    soft_bounces STRING,
    hard_bounces STRING,
    optOutReason STRING,
    dateLastEmailed STRING,
    ipSubscribed STRING,
    subPassword STRING,
    title STRING,
    mi STRING,
    aptNo STRING,
    registrationComments STRING,
    website STRING,
    dateRegistered TIMESTAMP,
    Lead STRING,
    customRMAMessageID STRING,
    customTrackingMessageID FLOAT64,
    AIAUPSACC STRING,
    Sfname STRING,
    SfCompanyName STRING,
    sfaddress STRING,
    sfcity STRING,
    sfzip INT64,
    sfphone STRING,
    sfstate STRING,
    sfcountry STRING,
    sfVerified STRING,
    TPAttn STRING,
    TPAdd STRING,
    TPCity STRING,
    TPState STRING,
    TPZip STRING,
    TPCompany STRING,
    CustPartnerID STRING,
    InsuranceValue FLOAT64,
    DeliveryConf FLOAT64,
    shipacc STRING,
    pricelist FLOAT64,
    customercat STRING,
    CustomCat BOOL,
    customSku BOOL,
    shippingCompany STRING,
    dropship BOOL,
    idfeedback FLOAT64,
    FeedbackStatus INT64,
    DontAskSurvey INT64,
    QBBatch INT64,
    VerifyAccountDate STRING,
    Rep STRING,
    isCCFeeApply FLOAT64,
    ShippingAddress2 STRING,
    PORequired BOOL,
    isShowInventory FLOAT64,
    IsFreeShippingAvailable FLOAT64,
    CreditLimit INT64,
    CreditTerm INT64,
    shiptimereq STRING,
    ExchRate FLOAT64,
    CCidorder STRING,
    CoopPercentage FLOAT64,
    RepPercentage FLOAT64,
    SalesCommission FLOAT64,
    DefaultFeePercentage FLOAT64,
    IsAutomaticallySendInvoice BOOL,
    InvoiceEmailAddresses STRING,
    IsAllowDirectPO STRING,
    SalesType STRING,
    CustomerType STRING,
    SalesCountry STRING,
    PyleFBAName STRING,
    isNewCustomer INT64,
    ARInvoicing STRING,
    AccountPaymentMethod STRING
);

-- Merge data from temp table to main table
MERGE `{bq_project}.{bq_dataset}.{table_name}` AS MAIN
USING `{bq_project}.{bq_dataset}.{temp_table_name}` AS TEMP
ON MAIN.idcustomer = TEMP.idcustomer
WHEN MATCHED THEN
    UPDATE SET
        MAIN.idcustomer = TEMP.idcustomer,
        MAIN.name = TEMP.name,
        MAIN.lastName = TEMP.lastName,
        MAIN.customerCompany = TEMP.customerCompany,
        MAIN.phone = TEMP.phone,
        MAIN.fax = TEMP.fax,
        MAIN.homephone = TEMP.homephone,
        MAIN.mobile = TEMP.mobile,
        MAIN.yearsinbiz = TEMP.yearsinbiz,
        MAIN.annualsales = TEMP.annualsales,
        MAIN.productline = TEMP.productline,
        MAIN.lineofbiz = TEMP.lineofbiz,
        MAIN.comments = TEMP.comments,
        MAIN.lastlogin = TEMP.lastlogin,
        MAIN.account = TEMP.account,
        MAIN.taxid = TEMP.taxid,
        MAIN.taxcheck = TEMP.taxcheck,
        MAIN.history = TEMP.history,
        MAIN.email = TEMP.email,
        MAIN.password = TEMP.password,
        MAIN.address = TEMP.address,
        MAIN.zip = TEMP.zip,
        MAIN.stateCode = TEMP.stateCode,
        MAIN.state = TEMP.state,
        MAIN.city = TEMP.city,
        MAIN.countryCode = TEMP.countryCode,
        MAIN.shippingName = TEMP.shippingName,
        MAIN.shippingLastName = TEMP.shippingLastName,
        MAIN.shippingaddress = TEMP.shippingaddress,
        MAIN.shippingcity = TEMP.shippingcity,
        MAIN.shippingStateCode = TEMP.shippingStateCode,
        MAIN.shippingState = TEMP.shippingState,
        MAIN.shippingCountryCode = TEMP.shippingCountryCode,
        MAIN.shippingZip = TEMP.shippingZip,
        MAIN.wapAccess = TEMP.wapAccess,
        MAIN.active = TEMP.active,
        MAIN.idCustomerType = TEMP.idCustomerType,
        MAIN.refNumber = TEMP.refNumber,
        MAIN.status = TEMP.status,
        MAIN.daterequested = TEMP.daterequested,
        MAIN.dateapproved = TEMP.dateapproved,
        MAIN.idLanguage = TEMP.idLanguage,
        MAIN.bonusPoints = TEMP.bonusPoints,
        MAIN.flag = TEMP.flag,
        MAIN.handlingFee = TEMP.handlingFee,
        MAIN.myUpsFee = TEMP.myUpsFee,
        MAIN.chargeActivationFee = TEMP.chargeActivationFee,
        MAIN.canUseUPSaccount = TEMP.canUseUPSaccount,
        MAIN.fromShippingZip = TEMP.fromShippingZip,
        MAIN.timesMailedHtml = TEMP.timesMailedHtml,
        MAIN.timesMailedText = TEMP.timesMailedText,
        MAIN.prefers = TEMP.prefers,
        MAIN.confirmed = TEMP.confirmed,
        MAIN.dateSubscribed = TEMP.dateSubscribed,
        MAIN.dateLastUpdated = TEMP.dateLastUpdated,
        MAIN.customSubField1 = TEMP.customSubField1,
        MAIN.customSubField2 = TEMP.customSubField2,
        MAIN.customSubField3 = TEMP.customSubField3,
        MAIN.soft_bounces = TEMP.soft_bounces,
        MAIN.hard_bounces = TEMP.hard_bounces,
        MAIN.optOutReason = TEMP.optOutReason,
        MAIN.dateLastEmailed = TEMP.dateLastEmailed,
        MAIN.ipSubscribed = TEMP.ipSubscribed,
        MAIN.subPassword = TEMP.subPassword,
        MAIN.title = TEMP.title,
        MAIN.mi = TEMP.mi,
        MAIN.aptNo = TEMP.aptNo,
        MAIN.registrationComments = TEMP.registrationComments,
        MAIN.website = TEMP.website,
        MAIN.dateRegistered = TEMP.dateRegistered,
        MAIN.Lead = TEMP.Lead,
        MAIN.customRMAMessageID = TEMP.customRMAMessageID,
        MAIN.customTrackingMessageID = TEMP.customTrackingMessageID,
        MAIN.AIAUPSACC = TEMP.AIAUPSACC,
        MAIN.Sfname = TEMP.Sfname,
        MAIN.SfCompanyName = TEMP.SfCompanyName,
        MAIN.sfaddress = TEMP.sfaddress,
        MAIN.sfcity = TEMP.sfcity,
        MAIN.sfzip = TEMP.sfzip,
        MAIN.sfphone = TEMP.sfphone,
        MAIN.sfstate = TEMP.sfstate,
        MAIN.sfcountry = TEMP.sfcountry,
        MAIN.sfVerified = TEMP.sfVerified,
        MAIN.TPAttn = TEMP.TPAttn,
        MAIN.TPAdd = TEMP.TPAdd,
        MAIN.TPCity = TEMP.TPCity,
        MAIN.TPState = TEMP.TPState,
        MAIN.TPZip = TEMP.TPZip,
        MAIN.TPCompany = TEMP.TPCompany,
        MAIN.CustPartnerID = TEMP.CustPartnerID,
        MAIN.InsuranceValue = TEMP.InsuranceValue,
        MAIN.DeliveryConf = TEMP.DeliveryConf,
        MAIN.shipacc = TEMP.shipacc,
        MAIN.pricelist = TEMP.pricelist,
        MAIN.customercat = TEMP.customercat,
        MAIN.CustomCat = TEMP.CustomCat,
        MAIN.customSku = TEMP.customSku,
        MAIN.shippingCompany = TEMP.shippingCompany,
        MAIN.dropship = TEMP.dropship,
        MAIN.idfeedback = TEMP.idfeedback,
        MAIN.FeedbackStatus = TEMP.FeedbackStatus,
        MAIN.DontAskSurvey = TEMP.DontAskSurvey,
        MAIN.QBBatch = TEMP.QBBatch,
        MAIN.VerifyAccountDate = TEMP.VerifyAccountDate,
        MAIN.Rep = TEMP.Rep,
        MAIN.isCCFeeApply = TEMP.isCCFeeApply,
        MAIN.ShippingAddress2 = TEMP.ShippingAddress2,
        MAIN.PORequired = TEMP.PORequired,
        MAIN.isShowInventory = TEMP.isShowInventory,
        MAIN.IsFreeShippingAvailable = TEMP.IsFreeShippingAvailable,
        MAIN.CreditLimit = TEMP.CreditLimit,
        MAIN.CreditTerm = TEMP.CreditTerm,
        MAIN.shiptimereq = TEMP.shiptimereq,
        MAIN.ExchRate = TEMP.ExchRate,
        MAIN.CCidorder = TEMP.CCidorder,
        MAIN.CoopPercentage = TEMP.CoopPercentage,
        MAIN.RepPercentage = TEMP.RepPercentage,
        MAIN.SalesCommission = TEMP.SalesCommission,
        MAIN.DefaultFeePercentage = TEMP.DefaultFeePercentage,
        MAIN.IsAutomaticallySendInvoice = TEMP.IsAutomaticallySendInvoice,
        MAIN.InvoiceEmailAddresses = TEMP.InvoiceEmailAddresses,
        MAIN.IsAllowDirectPO = TEMP.IsAllowDirectPO,
        MAIN.SalesType = TEMP.SalesType,
        MAIN.CustomerType = TEMP.CustomerType,
        MAIN.SalesCountry = TEMP.SalesCountry,
        MAIN.PyleFBAName = TEMP.PyleFBAName,
        MAIN.isNewCustomer = TEMP.isNewCustomer,
        MAIN.ARInvoicing = TEMP.ARInvoicing,
        MAIN.AccountPaymentMethod = TEMP.AccountPaymentMethod
WHEN NOT MATCHED THEN
INSERT VALUES (
    TEMP.idcustomer,
    TEMP.name,
    TEMP.lastName,
    TEMP.customerCompany,
    TEMP.phone,
    TEMP.fax,
    TEMP.homephone,
    TEMP.mobile,
    TEMP.yearsinbiz,
    TEMP.annualsales,
    TEMP.productline,
    TEMP.lineofbiz,
    TEMP.comments,
    TEMP.lastlogin,
    TEMP.account,
    TEMP.taxid,
    TEMP.taxcheck,
    TEMP.history,
    TEMP.email,
    TEMP.password,
    TEMP.address,
    TEMP.zip,
    TEMP.stateCode,
    TEMP.state,
    TEMP.city,
    TEMP.countryCode,
    TEMP.shippingName,
    TEMP.shippingLastName,
    TEMP.shippingaddress,
    TEMP.shippingcity,
    TEMP.shippingStateCode,
    TEMP.shippingState,
    TEMP.shippingCountryCode,
    TEMP.shippingZip,
    TEMP.wapAccess,
    TEMP.active,
    TEMP.idCustomerType,
    TEMP.refNumber,
    TEMP.status,
    TEMP.daterequested,
    TEMP.dateapproved,
    TEMP.idLanguage,
    TEMP.bonusPoints,
    TEMP.flag,
    TEMP.handlingFee,
    TEMP.myUpsFee,
    TEMP.chargeActivationFee,
    TEMP.canUseUPSaccount,
    TEMP.fromShippingZip,
    TEMP.timesMailedHtml,
    TEMP.timesMailedText,
    TEMP.prefers,
    TEMP.confirmed,
    TEMP.dateSubscribed,
    TEMP.dateLastUpdated,
    TEMP.customSubField1,
    TEMP.customSubField2,
    TEMP.customSubField3,
    TEMP.soft_bounces,
    TEMP.hard_bounces,
    TEMP.optOutReason,
    TEMP.dateLastEmailed,
    TEMP.ipSubscribed,
    TEMP.subPassword,
    TEMP.title,
    TEMP.mi,
    TEMP.aptNo,
    TEMP.registrationComments,
    TEMP.website,
    TEMP.dateRegistered,
    TEMP.Lead,
    TEMP.customRMAMessageID,
    TEMP.customTrackingMessageID,
    TEMP.AIAUPSACC,
    TEMP.Sfname,
    TEMP.SfCompanyName,
    TEMP.sfaddress,
    TEMP.sfcity,
    TEMP.sfzip,
    TEMP.sfphone,
    TEMP.sfstate,
    TEMP.sfcountry,
    TEMP.sfVerified,
    TEMP.TPAttn,
    TEMP.TPAdd,
    TEMP.TPCity,
    TEMP.TPState,
    TEMP.TPZip,
    TEMP.TPCompany,
    TEMP.CustPartnerID,
    TEMP.InsuranceValue,
    TEMP.DeliveryConf,
    TEMP.shipacc,
    TEMP.pricelist,
    TEMP.customercat,
    TEMP.CustomCat,
    TEMP.customSku,
    TEMP.shippingCompany,
    TEMP.dropship,
    TEMP.idfeedback,
    TEMP.FeedbackStatus,
    TEMP.DontAskSurvey,
    TEMP.QBBatch,
    TEMP.VerifyAccountDate,
    TEMP.Rep,
    TEMP.isCCFeeApply,
    TEMP.ShippingAddress2,
    TEMP.PORequired,
    TEMP.isShowInventory,
    TEMP.IsFreeShippingAvailable,
    TEMP.CreditLimit,
    TEMP.CreditTerm,
    TEMP.shiptimereq,
    TEMP.ExchRate,
    TEMP.CCidorder,
    TEMP.CoopPercentage,
    TEMP.RepPercentage,
    TEMP.SalesCommission,
    TEMP.DefaultFeePercentage,
    TEMP.IsAutomaticallySendInvoice,
    TEMP.InvoiceEmailAddresses,
    TEMP.IsAllowDirectPO,
    TEMP.SalesType,
    TEMP.CustomerType,
    TEMP.SalesCountry,
    TEMP.PyleFBAName,
    TEMP.isNewCustomer,
    TEMP.ARInvoicing,
    TEMP.AccountPaymentMethod
)
