-- Create main table if not exists
CREATE TABLE IF NOT EXISTS {bq_project}.{bq_dataset}.{table_name} (
    idOrder INT64,
    OLDorderDate STRING,
    orderDate DATE,
    idCustomer INT64 DEFAULT 0,
    details STRING,
    total FLOAT64 DEFAULT 0.0,
    address STRING,
    zip STRING,
    stateCode STRING,
    state STRING,
    city STRING,
    countryCode STRING,
    obs STRING,
    taxAmount FLOAT64 DEFAULT 0.0,
    shipmentDetails STRING,
    paymentDetails STRING,
    discountDetails STRING,
    nroRan INT64 DEFAULT 0,
    shippingName STRING,
    shippingLastName STRING,
    shippingAddress STRING,
    ShippingAddress2 STRING,
    shippingStateCode STRING,
    shippingState STRING,
    shippingCity STRING,
    shippingCountryCode STRING,
    shippingZip STRING,
    orderStatus INT64 DEFAULT 0,
    viewed INT64 DEFAULT 0,
    digitalEmailText STRING,
    idAffiliate FLOAT64 DEFAULT 0,
    idCustomerType FLOAT64 DEFAULT 0,
    browserIp STRING,
    transactionResults STRING,
    shipmentTracking STRING,
    vatNumber STRING,
    idLanguage INT64 DEFAULT 0,
    wishListIdCustomer INT64 DEFAULT 0,
    user1 STRING,
    user2 FLOAT64,
    user3 INT64,
    invoiceNo INT64,
    myCustomNotes STRING,
    cancelReason STRING,
    customerPO STRING,
    Exported INT64 DEFAULT 0,
    amzOrder_item_id STRING,
    amzPayments_date STRING,
    amzBuyer_email STRING,
    amzBuyer_name STRING,
    amzBuyer_phone STRING,
    amzShip_phone_number STRING,
    shipToCompany STRING,
    shipmentAmount FLOAT64,
    sigRequired FLOAT64,
    orderDeclaredValue STRING,
    orderPhone STRING,
    shipmentDisAmt FLOAT64,
    ExpToCust BOOLEAN,
    ShipDate TIMESTAMP,
    duty FLOAT64,
    PromisDate DATE,
    Printed BOOLEAN,
    PrintedDate TIMESTAMP,
    CustRefPO STRING,
    CustPaid STRING,
    PrintBatchId STRING,
    idUser STRING,
    ShipProcessDate STRING,
    QBExported STRING,
    EnteredBy FLOAT64,
    SalesChannel STRING,
    currency STRING,
    FeedbackRequest STRING,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    OrdersSystem STRING,
    OrderFileName STRING,
    cancelReasonComment STRING,
    DiscountCode STRING,
    UserName STRING,
    IdBol FLOAT64,
    idUserPrinted FLOAT64,
    WhoShipped FLOAT64,
    ccFee FLOAT64,
    Salestax FLOAT64,
    InvDate DATE,
    UpsShipStatus STRING,
    actualDeliveryDate STRING,
    TermDesc INT64,
    Ticket_Id INT64,
    isCustomReviewEmailSent STRING,
    UpsShipStatusLastUpdated STRING,
    AMALabelShipmentId STRING,
    latestDeliveryDate DATE,
    STID STRING,
    InvoiceType STRING,
    IsOrderMisMatch STRING,
    NewOrderStatus STRING,
    NewBOLID STRING,
    TotalCTN STRING,
    TotalPCS STRING,
    TotalWeight STRING,
    TotalCuft STRING,
    IdOrderWarehouse STRING,
    CSSIEnteredBy STRING,
    ShipStatus STRING,
    IsEmailSend BOOL,
    Received945 STRING,
    AmazonCTNS STRING,
    PickSheetPrintedBy STRING,
    Pallet STRING,
    Tag STRING,
    PrintedOrderResetBy INT64,
    PrintedOrderResetDate TIMESTAMP,
    IsFBARepackShipment BOOLEAN,
    ShipmentReadyDate TIMESTAMP,
    OrderCancelDate TIMESTAMP
);

-- Merge data from temp table to main table
MERGE {bq_project}.{bq_dataset}.{table_name} AS MAIN
USING {bq_project}.{bq_dataset}.{temp_table_name} AS TEMP
ON MAIN.idOrder = temp.idOrder
WHEN MATCHED THEN
    UPDATE SET
        MAIN.idOrder = TEMP.idOrder,
        MAIN.OLDorderDate = TEMP.OLDorderDate,
        MAIN.orderDate = TEMP.orderDate,
        MAIN.idCustomer = TEMP.idCustomer,
        MAIN.details = TEMP.details,
        MAIN.total = TEMP.total,
        MAIN.address = TEMP.address,
        MAIN.zip = TEMP.zip,
        MAIN.stateCode = TEMP.stateCode,
        MAIN.state = TEMP.state,
        MAIN.city = TEMP.city,
        MAIN.countryCode = TEMP.countryCode,
        MAIN.obs = TEMP.obs,
        MAIN.taxAmount = TEMP.taxAmount,
        MAIN.shipmentDetails = TEMP.shipmentDetails,
        MAIN.paymentDetails = TEMP.paymentDetails,
        MAIN.discountDetails = TEMP.discountDetails,
        MAIN.nroRan = TEMP.nroRan,
        MAIN.shippingName = TEMP.shippingName,
        MAIN.shippingLastName = TEMP.shippingLastName,
        MAIN.shippingAddress = TEMP.shippingAddress,
        MAIN.ShippingAddress2 = TEMP.ShippingAddress2,
        MAIN.shippingStateCode = TEMP.shippingStateCode,
        MAIN.shippingState = TEMP.shippingState,
        MAIN.shippingCity = TEMP.shippingCity,
        MAIN.shippingCountryCode = TEMP.shippingCountryCode,
        MAIN.shippingZip = TEMP.shippingZip,
        MAIN.orderStatus = TEMP.orderStatus,
        MAIN.viewed = TEMP.viewed,
        MAIN.digitalEmailText = TEMP.digitalEmailText,
        MAIN.idAffiliate = TEMP.idAffiliate,
        MAIN.idCustomerType = TEMP.idCustomerType,
        MAIN.browserIp = TEMP.browserIp,
        MAIN.transactionResults = TEMP.transactionResults,
        MAIN.shipmentTracking = TEMP.shipmentTracking,
        MAIN.vatNumber = TEMP.vatNumber,
        MAIN.idLanguage = TEMP.idLanguage,
        MAIN.wishListIdCustomer = TEMP.wishListIdCustomer,
        MAIN.user1 = TEMP.user1,
        MAIN.user2 = TEMP.user2,
        MAIN.user3 = TEMP.user3,
        MAIN.invoiceNo = TEMP.invoiceNo,
        MAIN.myCustomNotes = TEMP.myCustomNotes,
        MAIN.cancelReason = TEMP.cancelReason,
        MAIN.customerPO = TEMP.customerPO,
        MAIN.Exported = TEMP.Exported,
        MAIN.amzOrder_item_id = TEMP.amzOrder_item_id,
        MAIN.amzPayments_date = TEMP.amzPayments_date,
        MAIN.amzBuyer_email = TEMP.amzBuyer_email,
        MAIN.amzBuyer_name = TEMP.amzBuyer_name,
        MAIN.amzBuyer_phone = TEMP.amzBuyer_phone,
        MAIN.amzShip_phone_number = TEMP.amzShip_phone_number,
        MAIN.shipToCompany = TEMP.shipToCompany,
        MAIN.shipmentAmount = TEMP.shipmentAmount,
        MAIN.sigRequired = TEMP.sigRequired,
        MAIN.orderDeclaredValue = TEMP.orderDeclaredValue,
        MAIN.orderPhone = TEMP.orderPhone,
        MAIN.shipmentDisAmt = TEMP.shipmentDisAmt,
        MAIN.ExpToCust = TEMP.ExpToCust,
        MAIN.ShipDate = TEMP.ShipDate,
        MAIN.duty = TEMP.duty,
        MAIN.PromisDate = TEMP.PromisDate,
        MAIN.Printed = TEMP.Printed,
        MAIN.PrintedDate = TEMP.PrintedDate,
        MAIN.CustRefPO = TEMP.CustRefPO,
        MAIN.CustPaid = TEMP.CustPaid,
        MAIN.PrintBatchId = TEMP.PrintBatchId,
        MAIN.idUser = TEMP.idUser,
        MAIN.ShipProcessDate = TEMP.ShipProcessDate,
        MAIN.QBExported = TEMP.QBExported,
        MAIN.EnteredBy = TEMP.EnteredBy,
        MAIN.SalesChannel = TEMP.SalesChannel,
        MAIN.currency = TEMP.currency,
        MAIN.FeedbackRequest = TEMP.FeedbackRequest,
        MAIN.DateCreated = TEMP.DateCreated,
        MAIN.OrdersSystem = TEMP.OrdersSystem,
        MAIN.OrderFileName = TEMP.OrderFileName,
        MAIN.cancelReasonComment = TEMP.cancelReasonComment,
        MAIN.DiscountCode = TEMP.DiscountCode,
        MAIN.UserName = TEMP.UserName,
        MAIN.IdBol = TEMP.IdBol,
        MAIN.idUserPrinted = TEMP.idUserPrinted,
        MAIN.WhoShipped = TEMP.WhoShipped,
        MAIN.ccFee = TEMP.ccFee,
        MAIN.Salestax = TEMP.Salestax,
        MAIN.InvDate = TEMP.InvDate,
        MAIN.UpsShipStatus = TEMP.UpsShipStatus,
        MAIN.actualDeliveryDate = TEMP.actualDeliveryDate,
        MAIN.TermDesc = TEMP.TermDesc,
        MAIN.Ticket_Id = TEMP.Ticket_Id,
        MAIN.isCustomReviewEmailSent = TEMP.isCustomReviewEmailSent,
        MAIN.UpsShipStatusLastUpdated = TEMP.UpsShipStatusLastUpdated,
        MAIN.AMALabelShipmentId = TEMP.AMALabelShipmentId,
        MAIN.latestDeliveryDate = TEMP.latestDeliveryDate,
        MAIN.STID = TEMP.STID,
        MAIN.InvoiceType = TEMP.InvoiceType,
        MAIN.IsOrderMisMatch = TEMP.IsOrderMisMatch,
        MAIN.NewOrderStatus = TEMP.NewOrderStatus,
        MAIN.NewBOLID = TEMP.NewBOLID,
        MAIN.TotalCTN = TEMP.TotalCTN,
        MAIN.TotalPCS = TEMP.TotalPCS,
        MAIN.TotalWeight = TEMP.TotalWeight,
        MAIN.TotalCuft = TEMP.TotalCuft,
        MAIN.IdOrderWarehouse = TEMP.IdOrderWarehouse,
        MAIN.CSSIEnteredBy = TEMP.CSSIEnteredBy,
        MAIN.ShipStatus = TEMP.ShipStatus,
        MAIN.IsEmailSend = TEMP.IsEmailSend,
        MAIN.Received945 = TEMP.Received945,
        MAIN.AmazonCTNS = TEMP.AmazonCTNS,
        MAIN.PickSheetPrintedBy = TEMP.PickSheetPrintedBy,
        MAIN.Pallet = TEMP.Pallet,
        MAIN.Tag = TEMP.Tag,
        MAIN.PrintedOrderResetBy = TEMP.PrintedOrderResetBy,
        MAIN.PrintedOrderResetDate = TEMP.PrintedOrderResetDate,
        MAIN.IsFBARepackShipment = TEMP.IsFBARepackShipment,
        MAIN.ShipmentReadyDate = TEMP.ShipmentReadyDate,
        MAIN.OrderCancelDate = TEMP.OrderCancelDate
WHEN NOT MATCHED THEN
INSERT VALUES (
    TEMP.idOrder,
    TEMP.OLDorderDate,
    TEMP.orderDate,
    TEMP.idCustomer,
    TEMP.details,
    TEMP.total,
    TEMP.address,
    TEMP.zip,
    TEMP.stateCode,
    TEMP.state,
    TEMP.city,
    TEMP.countryCode,
    TEMP.obs,
    TEMP.taxAmount,
    TEMP.shipmentDetails,
    TEMP.paymentDetails,
    TEMP.discountDetails,
    TEMP.nroRan,
    TEMP.shippingName,
    TEMP.shippingLastName,
    TEMP.shippingAddress,
    TEMP.ShippingAddress2,
    TEMP.shippingStateCode,
    TEMP.shippingState,
    TEMP.shippingCity,
    TEMP.shippingCountryCode,
    TEMP.shippingZip,
    TEMP.orderStatus,
    TEMP.viewed,
    TEMP.digitalEmailText,
    TEMP.idAffiliate,
    TEMP.idCustomerType,
    TEMP.browserIp,
    TEMP.transactionResults,
    TEMP.shipmentTracking,
    TEMP.vatNumber,
    TEMP.idLanguage,
    TEMP.wishListIdCustomer,
    TEMP.user1,
    TEMP.user2,
    TEMP.user3,
    TEMP.invoiceNo,
    TEMP.myCustomNotes,
    TEMP.cancelReason,
    TEMP.customerPO,
    TEMP.Exported,
    TEMP.amzOrder_item_id,
    TEMP.amzPayments_date,
    TEMP.amzBuyer_email,
    TEMP.amzBuyer_name,
    TEMP.amzBuyer_phone,
    TEMP.amzShip_phone_number,
    TEMP.shipToCompany,
    TEMP.shipmentAmount,
    TEMP.sigRequired,
    TEMP.orderDeclaredValue,
    TEMP.orderPhone,
    TEMP.shipmentDisAmt,
    TEMP.ExpToCust,
    TEMP.ShipDate,
    TEMP.duty,
    TEMP.PromisDate,
    TEMP.Printed,
    TEMP.PrintedDate,
    TEMP.CustRefPO,
    TEMP.CustPaid,
    TEMP.PrintBatchId,
    TEMP.idUser,
    TEMP.ShipProcessDate,
    TEMP.QBExported,
    TEMP.EnteredBy,
    TEMP.SalesChannel,
    TEMP.currency,
    TEMP.FeedbackRequest,
    TEMP.DateCreated,
    TEMP.OrdersSystem,
    TEMP.OrderFileName,
    TEMP.cancelReasonComment,
    TEMP.DiscountCode,
    TEMP.UserName,
    TEMP.IdBol,
    TEMP.idUserPrinted,
    TEMP.WhoShipped,
    TEMP.ccFee,
    TEMP.Salestax,
    TEMP.InvDate,
    TEMP.UpsShipStatus,
    TEMP.actualDeliveryDate,
    TEMP.TermDesc,
    TEMP.Ticket_Id,
    TEMP.isCustomReviewEmailSent,
    TEMP.UpsShipStatusLastUpdated,
    TEMP.AMALabelShipmentId,
    TEMP.latestDeliveryDate,
    TEMP.STID,
    TEMP.InvoiceType,
    TEMP.IsOrderMisMatch,
    TEMP.NewOrderStatus,
    TEMP.NewBOLID,
    TEMP.TotalCTN,
    TEMP.TotalPCS,
    TEMP.TotalWeight,
    TEMP.TotalCuft,
    TEMP.IdOrderWarehouse,
    TEMP.CSSIEnteredBy,
    TEMP.ShipStatus,
    TEMP.IsEmailSend,
    TEMP.Received945,
    TEMP.AmazonCTNS,
    TEMP.PickSheetPrintedBy,
    TEMP.Pallet,
    TEMP.Tag,
    TEMP.PrintedOrderResetBy,
    TEMP.PrintedOrderResetDate,
    TEMP.IsFBARepackShipment,
    TEMP.ShipmentReadyDate,
    TEMP.OrderCancelDate
)
