-- Create main table if not exists
CREATE TABLE IF NOT EXISTS {bq_project}.{bq_dataset}.{table_name} (
    idSupplier INT64,
    supplierName STRING,
    supplierEmail STRING,
    supplierAddress STRING,
    supplierZip INT64,
    supplierCity STRING,
    supplierStateCode STRING,
    supplierAnotherState STRING,
    supplierCountryCode STRING,
    supplierPhone STRING,
    receiveSellEmail STRING,
    receiveUnderStockAlert STRING,
    StockActive INT64,
    idwarehouse INT64,
    Active BOOL,
    SupplierCompany STRING,
    CompanyName STRING,
    PrimaryContactName STRING,
    Note STRING,
    SupplierVendorCode STRING,
    SupplierNickNameSearch STRING,
    FromAddress STRING,
    FromCityStZip STRING,
    FromCompany STRING,
    creditlimit INT64,
    terms STRING,
    ItemNotInStockAlert INT64,
    FaxNumber STRING,
    NoOfDaysOutofStock INT64,
    ItemsArrivingSoonAlert INT64,
    SupplierAddress2 STRING,
    HandlingFee INT64,
    HandlingFeeFor INT64,
    lastUpload STRING,
    ReturnNote STRING,
    ShippingType INT64,
    Alert BOOL,
    DateSupAdded TIMESTAMP,
    StockDelayDays INT64,
    SupOnorderStockDelayDays INT64,
    MoveAllStockToOnorder BOOL,
    MarkStockZero STRING,
    MarkStockZeroCondition STRING,
    MarkOnOrderZero STRING,
    MarkOnOrderZeroCondition STRING,
    DefaultDutyPercent INT64,
    DefaultContainerCost INT64,
    PortID INT64,
    isDefaultDutyPercentZero BOOL,
    isDefaultContainerCostZero BOOL,
    SupplierPassword STRING,
    AlternateEmail STRING
);

-- Merge data from temp table to main table
MERGE {bq_project}.{bq_dataset}.{table_name} AS MAIN
USING {bq_project}.{bq_dataset}.temp_{table_name} AS TEMP
ON MAIN.idSupplier = TEMP.idSupplier
WHEN MATCHED THEN
    UPDATE SET
        MAIN.idSupplier = TEMP.idSupplier,
        MAIN.supplierName = TEMP.supplierName,
        MAIN.supplierEmail = TEMP.supplierEmail,
        MAIN.supplierAddress = TEMP.supplierAddress,
        MAIN.supplierZip = TEMP.supplierZip,
        MAIN.supplierCity = TEMP.supplierCity,
        MAIN.supplierStateCode = TEMP.supplierStateCode,
        MAIN.supplierAnotherState = TEMP.supplierAnotherState,
        MAIN.supplierCountryCode = TEMP.supplierCountryCode,
        MAIN.supplierPhone = TEMP.supplierPhone,
        MAIN.receiveSellEmail = TEMP.receiveSellEmail,
        MAIN.receiveUnderStockAlert = TEMP.receiveUnderStockAlert,
        MAIN.StockActive = TEMP.StockActive,
        MAIN.idwarehouse = TEMP.idwarehouse,
        MAIN.Active = TEMP.Active,
        MAIN.SupplierCompany = TEMP.SupplierCompany,
        MAIN.CompanyName = TEMP.CompanyName,
        MAIN.PrimaryContactName = TEMP.PrimaryContactName,
        MAIN.Note = TEMP.Note,
        MAIN.SupplierVendorCode = TEMP.SupplierVendorCode,
        MAIN.SupplierNickNameSearch = TEMP.SupplierNickNameSearch,
        MAIN.FromAddress = TEMP.FromAddress,
        MAIN.FromCityStZip = TEMP.FromCityStZip,
        MAIN.FromCompany = TEMP.FromCompany,
        MAIN.creditlimit = TEMP.creditlimit,
        MAIN.terms = TEMP.terms,
        MAIN.ItemNotInStockAlert = TEMP.ItemNotInStockAlert,
        MAIN.FaxNumber = TEMP.FaxNumber,
        MAIN.NoOfDaysOutofStock = TEMP.NoOfDaysOutofStock,
        MAIN.ItemsArrivingSoonAlert = TEMP.ItemsArrivingSoonAlert,
        MAIN.SupplierAddress2 = TEMP.SupplierAddress2,
        MAIN.HandlingFee = TEMP.HandlingFee,
        MAIN.HandlingFeeFor = TEMP.HandlingFeeFor,
        MAIN.lastUpload = TEMP.lastUpload,
        MAIN.ReturnNote = TEMP.ReturnNote,
        MAIN.ShippingType = TEMP.ShippingType,
        MAIN.Alert = TEMP.Alert,
        MAIN.DateSupAdded = TEMP.DateSupAdded,
        MAIN.StockDelayDays = TEMP.StockDelayDays,
        MAIN.SupOnorderStockDelayDays = TEMP.SupOnorderStockDelayDays,
        MAIN.MoveAllStockToOnorder = TEMP.MoveAllStockToOnorder,
        MAIN.MarkStockZero = TEMP.MarkStockZero,
        MAIN.MarkStockZeroCondition = TEMP.MarkStockZeroCondition,
        MAIN.MarkOnOrderZero = TEMP.MarkOnOrderZero,
        MAIN.MarkOnOrderZeroCondition = TEMP.MarkOnOrderZeroCondition,
        MAIN.DefaultDutyPercent = TEMP.DefaultDutyPercent,
        MAIN.DefaultContainerCost = TEMP.DefaultContainerCost,
        MAIN.PortID = TEMP.PortID,
        MAIN.isDefaultDutyPercentZero = TEMP.isDefaultDutyPercentZero,
        MAIN.isDefaultContainerCostZero = TEMP.isDefaultContainerCostZero,
        MAIN.SupplierPassword = TEMP.SupplierPassword,
        MAIN.AlternateEmail = TEMP.AlternateEmail
WHEN NOT MATCHED THEN
INSERT VALUES (
    TEMP.idSupplier,
    TEMP.supplierName,
    TEMP.supplierEmail,
    TEMP.supplierAddress,
    TEMP.supplierZip,
    TEMP.supplierCity,
    TEMP.supplierStateCode,
    TEMP.supplierAnotherState,
    TEMP.supplierCountryCode,
    TEMP.supplierPhone,
    TEMP.receiveSellEmail,
    TEMP.receiveUnderStockAlert,
    TEMP.StockActive,
    TEMP.idwarehouse,
    TEMP.Active,
    TEMP.SupplierCompany,
    TEMP.CompanyName,
    TEMP.PrimaryContactName,
    TEMP.Note,
    TEMP.SupplierVendorCode,
    TEMP.SupplierNickNameSearch,
    TEMP.FromAddress,
    TEMP.FromCityStZip,
    TEMP.FromCompany,
    TEMP.creditlimit,
    TEMP.terms,
    TEMP.ItemNotInStockAlert,
    TEMP.FaxNumber,
    TEMP.NoOfDaysOutofStock,
    TEMP.ItemsArrivingSoonAlert,
    TEMP.SupplierAddress2,
    TEMP.HandlingFee,
    TEMP.HandlingFeeFor,
    TEMP.lastUpload,
    TEMP.ReturnNote,
    TEMP.ShippingType,
    TEMP.Alert,
    TEMP.DateSupAdded,
    TEMP.StockDelayDays,
    TEMP.SupOnorderStockDelayDays,
    TEMP.MoveAllStockToOnorder,
    TEMP.MarkStockZero,
    TEMP.MarkStockZeroCondition,
    TEMP.MarkOnOrderZero,
    TEMP.MarkOnOrderZeroCondition,
    TEMP.DefaultDutyPercent,
    TEMP.DefaultContainerCost,
    TEMP.PortID,
    TEMP.isDefaultDutyPercentZero,
    TEMP.isDefaultContainerCostZero,
    TEMP.SupplierPassword,
    TEMP.AlternateEmail
)
