-- Create main table if not exists
CREATE TABLE IF NOT EXISTS {bq_project}.{bq_dataset}.{table_name} (
    idVendorProducts INT64,
    idUpc INT64,
    idSupplier INT64,
    Vendorsku STRING,
    Model STRING,
    FOBPrice FLOAT64,
    FOBCHNG STRING,
    Duty FLOAT64,
    ft FLOAT64,
    ct INT64,
    FREIGHT FLOAT64,
    LAND STRING,
    Commission FLOAT64,
    DutyPercent FLOAT64 DEFAULT 12,
    ContainerCost INT64 DEFAULT 4500,
    TruckCost1 INT64 DEFAULT 0,
    TruckCost2 INT64 DEFAULT 0,
    MCHeight FLOAT64,
    MCWidth FLOAT64,
    MCDepth FLOAT64,
    Dealer35 FLOAT64,
    L3_35 FLOAT64,
    P_35 FLOAT64,
    WhoAdded INT64,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    Note STRING,
    CalcLanded FLOAT64,
    `default` BOOLEAN,
    weight FLOAT64,
    PrdUnitWeight FLOAT64,
    MCGWeight FLOAT64,
    width FLOAT64,
    height FLOAT64,
    GBHeight FLOAT64,
    GBWidth FLOAT64,
    GBDepth FLOAT64,
    Depth FLOAT64,
    packed STRING,
    description STRING,
    details STRING,
    introduction STRING,
    specification STRING,
    TYPE1 STRING,
    TYPE2 STRING,
    TYPE3 STRING,
    `GROUP` STRING,
    SPECIAL BOOLEAN,
    Title40 STRING,
    ExpPrice FLOAT64,
    LastDateOrdered STRING,
    LastCost FLOAT64,
    LastQtyOrdered INT64,
    JanQty INT64,
    FebQty INT64,
    MarQty INT64,
    AprQty INT64,
    MayQty INT64,
    JunQty INT64,
    JulyQty INT64,
    AugQty INT64,
    SeptQty INT64,
    OctQty INT64,
    NovQty INT64,
    DecQty INT64,
    MTDQty INT64,
    MTDSale INT64,
    YTDQty INT64,
    YTDSale INT64,
    LTMSale INT64,
    LTMQty INT64,
    REPLACECOST FLOAT64,
    CSAVGcost FLOAT64 DEFAULT 0.0,
    CSInsideCost FLOAT64 DEFAULT 0.0,
    CSLPrice2 FLOAT64 DEFAULT 0.0,
    CSLPrice3 FLOAT64 DEFAULT 0.0,
    idBuyer INT64,
    CostEffectiveDate DATE,
    ShippingVolumne INT64
);

-- Merge data from temp table to main table
MERGE {bq_project}.{bq_dataset}.{table_name} AS MAIN
USING {bq_project}.{bq_dataset}.{temp_table_name} AS TEMP
ON MAIN.idVendorProducts = TEMP.idVendorProducts
WHEN MATCHED THEN
    UPDATE SET
        MAIN.idVendorProducts = TEMP.idVendorProducts,
        MAIN.idUpc = TEMP.idUpc,
        MAIN.idSupplier = TEMP.idSupplier,
        MAIN.Vendorsku = TEMP.Vendorsku,
        MAIN.Model = TEMP.Model,
        MAIN.FOBPrice = TEMP.FOBPrice,
        MAIN.FOBCHNG = TEMP.FOBCHNG,
        MAIN.Duty = TEMP.Duty,
        MAIN.ft = TEMP.ft,
        MAIN.ct = TEMP.ct,
        MAIN.FREIGHT = TEMP.FREIGHT,
        MAIN.LAND = TEMP.LAND,
        MAIN.Commission = TEMP.Commission,
        MAIN.DutyPercent = TEMP.DutyPercent,
        MAIN.ContainerCost = TEMP.ContainerCost,
        MAIN.TruckCost1 = TEMP.TruckCost1,
        MAIN.TruckCost2 = TEMP.TruckCost2,
        MAIN.MCHeight = TEMP.MCHeight,
        MAIN.MCWidth = TEMP.MCWidth,
        MAIN.MCDepth = TEMP.MCDepth,
        MAIN.Dealer35 = TEMP.Dealer35,
        MAIN.L3_35 = TEMP.L3_35,
        MAIN.P_35 = TEMP.P_35,
        MAIN.WhoAdded = TEMP.WhoAdded,
        MAIN.DateCreated = TEMP.DateCreated,
        MAIN.Note = TEMP.Note,
        MAIN.CalcLanded = TEMP.CalcLanded,
        MAIN.`default` = TEMP.`default`,
        MAIN.weight = TEMP.weight,
        MAIN.PrdUnitWeight = TEMP.PrdUnitWeight,
        MAIN.MCGWeight = TEMP.MCGWeight,
        MAIN.width = TEMP.width,
        MAIN.height = TEMP.height,
        MAIN.GBHeight = TEMP.GBHeight,
        MAIN.GBWidth = TEMP.GBWidth,
        MAIN.GBDepth = TEMP.GBDepth,
        MAIN.Depth = TEMP.Depth,
        MAIN.packed = TEMP.packed,
        MAIN.description = TEMP.description,
        MAIN.details = TEMP.details,
        MAIN.introduction = TEMP.introduction,
        MAIN.specification = TEMP.specification,
        MAIN.TYPE1 = TEMP.TYPE1,
        MAIN.TYPE2 = TEMP.TYPE2,
        MAIN.TYPE3 = TEMP.TYPE3,
        MAIN.`GROUP` = TEMP.`GROUP`,
        MAIN.SPECIAL = TEMP.SPECIAL,
        MAIN.Title40 = TEMP.Title40,
        MAIN.ExpPrice = TEMP.ExpPrice,
        MAIN.LastDateOrdered = TEMP.LastDateOrdered,
        MAIN.LastCost = TEMP.LastCost,
        MAIN.LastQtyOrdered = TEMP.LastQtyOrdered,
        MAIN.JanQty = TEMP.JanQty,
        MAIN.FebQty = TEMP.FebQty,
        MAIN.MarQty = TEMP.MarQty,
        MAIN.AprQty = TEMP.AprQty,
        MAIN.MayQty = TEMP.MayQty,
        MAIN.JunQty = TEMP.JunQty,
        MAIN.JulyQty = TEMP.JulyQty,
        MAIN.AugQty = TEMP.AugQty,
        MAIN.SeptQty = TEMP.SeptQty,
        MAIN.OctQty = TEMP.OctQty,
        MAIN.NovQty = TEMP.NovQty,
        MAIN.DecQty = TEMP.DecQty,
        MAIN.MTDQty = TEMP.MTDQty,
        MAIN.MTDSale = TEMP.MTDSale,
        MAIN.YTDQty = TEMP.YTDQty,
        MAIN.YTDSale = TEMP.YTDSale,
        MAIN.LTMSale = TEMP.LTMSale,
        MAIN.LTMQty = TEMP.LTMQty,
        MAIN.REPLACECOST = TEMP.REPLACECOST,
        MAIN.CSAVGcost = TEMP.CSAVGcost,
        MAIN.CSInsideCost = TEMP.CSInsideCost,
        MAIN.CSLPrice2 = TEMP.CSLPrice2,
        MAIN.CSLPrice3 = TEMP.CSLPrice3,
        MAIN.idBuyer = TEMP.idBuyer,
        MAIN.CostEffectiveDate = TEMP.CostEffectiveDate,
        MAIN.ShippingVolumne = TEMP.ShippingVolumne
WHEN NOT MATCHED THEN
INSERT VALUES (
    TEMP.idVendorProducts,
    TEMP.idUpc,
    TEMP.idSupplier,
    TEMP.Vendorsku,
    TEMP.Model,
    TEMP.FOBPrice,
    TEMP.FOBCHNG,
    TEMP.Duty,
    TEMP.ft,
    TEMP.ct,
    TEMP.FREIGHT,
    TEMP.LAND,
    TEMP.Commission,
    TEMP.DutyPercent,
    TEMP.ContainerCost,
    TEMP.TruckCost1,
    TEMP.TruckCost2,
    TEMP.MCHeight,
    TEMP.MCWidth,
    TEMP.MCDepth,
    TEMP.Dealer35,
    TEMP.L3_35,
    TEMP.P_35,
    TEMP.WhoAdded,
    TEMP.DateCreated,
    TEMP.Note,
    TEMP.CalcLanded,
    TEMP.`default`,
    TEMP.weight,
    TEMP.PrdUnitWeight,
    TEMP.MCGWeight,
    TEMP.width,
    TEMP.height,
    TEMP.GBHeight,
    TEMP.GBWidth,
    TEMP.GBDepth,
    TEMP.Depth,
    TEMP.packed,
    TEMP.description,
    TEMP.details,
    TEMP.introduction,
    TEMP.specification,
    TEMP.TYPE1,
    TEMP.TYPE2,
    TEMP.TYPE3,
    TEMP.`GROUP`,
    TEMP.SPECIAL,
    TEMP.Title40,
    TEMP.ExpPrice,
    TEMP.LastDateOrdered,
    TEMP.LastCost,
    TEMP.LastQtyOrdered,
    TEMP.JanQty,
    TEMP.FebQty,
    TEMP.MarQty,
    TEMP.AprQty,
    TEMP.MayQty,
    TEMP.JunQty,
    TEMP.JulyQty,
    TEMP.AugQty,
    TEMP.SeptQty,
    TEMP.OctQty,
    TEMP.NovQty,
    TEMP.DecQty,
    TEMP.MTDQty,
    TEMP.MTDSale,
    TEMP.YTDQty,
    TEMP.YTDSale,
    TEMP.LTMSale,
    TEMP.LTMQty,
    TEMP.REPLACECOST,
    TEMP.CSAVGcost,
    TEMP.CSInsideCost,
    TEMP.CSLPrice2,
    TEMP.CSLPrice3,
    TEMP.idBuyer,
    TEMP.CostEffectiveDate,
    TEMP.ShippingVolumne
)
