CREATE OR REPLACE TABLE {bq_project}.{bq_dataset}.{table_name} (
    idWarehouse INT64,
    idSupplier INT64,
    WName STRING,
    ContactName STRING,
    ContactPhone STRING,
    Address STRING,
    City STRING,
    State STRING,
    Zipcode STRING,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    Active INT64,
    StockActive BOOLEAN,
    ResetLocation INT64,
    Wcompnay STRING,
    UPSAcc STRING,
    DoNotUseForAutoAllocation INT64,
    jET_node_id STRING,
    EmailId STRING,
    StockDelayDays INT64,
    WHOnorderStockDelayDays INT64,
    GoFlowWName STRING,
    AmazonVCWarehouseCode STRING,
    AMZDFWorkbookName STRING,
    HomeDepotPickUpWarehouseCode STRING,
    WarehouseName STRING,
    warehouseCountry STRING
);