name: Deploy Cloud Run

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "messages/**"
      - ".github/workflows/deploy_cloud_run.yml"
  workflow_dispatch:

concurrency:
  group: "Cloud Run"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
    strategy:
      matrix:
        include:
          - message_file: admins.json
    steps:
      - uses: "actions/checkout@v4"

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ vars.PROJECT_ID }}

      - name: Create Cloud Scheduler
        id: scheduler
        run: |-
          echo "Creating Cloud Scheduler"
          gcloud scheduler jobs create http job_name \
            --uri "https://msssql-to-bq-fastpi-uydebvdw6a-uc.a.run.app/${{ vars.SERVICE_NAME }}" \
            --schedule "0 0 * * *" \
            --time-zone "IST" \
            --message-body-from-file "messages/${{ matrix.message_file }}" \
            --headers "Content-Type=application/json,User-Agent=Google-Cloud-Scheduler"
