name: Deploy Cloud Run

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "dag/**"
      - ".github/workflows/deploy_cloud_run.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
    steps:
      - uses: "actions/checkout@v4"

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ vars.PROJECT_ID }}

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ vars.REGION }}-docker.pkg.dev"

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}

      - name: Create Service declaration
        run: |-
          echo "Creating service declaration"
          export SERVICE_NAME=${{ vars.SERVICE_NAME }}
          export IMAGE=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}
          export SERVICE_ACCOUNT=mssql-to-bigquery@soundarounddatondw.iam.gserviceaccount.com
          export SSH_HOST=${{ vars.SSH_HOST }}
          export SSH_PORT=${{ vars.SSH_PORT }}
          export SSH_USERNAME=${{ vars.SSH_USERNAME }}
          export DB_HOST=${{ vars.DB_HOST }}
          export DB_PORT=${{ vars.DB_PORT }}
          export DB_USERNAME=${{ vars.DB_USERNAME }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_NAME=${{ vars.DB_NAME }}
          export BQ_PROJECT=${{ vars.PROJECT_ID }}
          export BQ_DATASET=${{ vars.BQ_DATASET }}
          export GCS_BUCKET=${{ vars.GCS_BUCKET }}

          envsubst < ./service-yaml/container.yaml > container.yaml
          cat container.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ vars.service_name }}
          region: ${{ vars.region }}
          metadata: container.yaml
